services:
 web:
  image: nginx
  networks:
   - net1
 back:
  image: openjdk:17-jdk-alpine
  working_dir: /app
  volumes:
   - ./back:/app
  command: sh -c "java -jar a.jar"
  networks:
   - net1
   - net2
 db:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=abc123
  networks:
   - net2
networks:
 net1:
  ipam:
   config:
    - subnet: 192.168.251.0/24
 net2:
  ipam:
   config:
    - subnet: 192.168.252.0/24
